# -*- coding: utf-8 -*-
"""Internshiptask5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Je_WHdQiksjJAzw2SPzyFGNtq6KFpbW

load the dataset
"""

import pandas as pd

df = pd.read_csv("/content/Accident_Information.csv", low_memory=False)
df.head()

"""Data processing"""

df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')
df['Hour'] = df['Datetime'].dt.hour

"""Time-based analysis"""

df['Hour'].value_counts().sort_index().plot(kind='line', title="Accidents by Hour")

"""Weather analysis"""

df['Weather_Conditions'].value_counts().head(10).plot(kind='bar')

"""Road condition analysis"""

df['Road_Surface_Conditions'].value_counts().plot(kind='bar')

"""Light condition"""

df['Light_Conditions'].value_counts().plot(kind='bar')

"""HOTSPOT MAP"""

import folium
from folium.plugins import HeatMap

map = folium.Map(location=[54, -2], zoom_start=6)

HeatMap(df[['Latitude','Longitude']].dropna().values.tolist()).add_to(map)

map